apiVersion: v1
kind: Service
metadata:
  name: infraops-service
  namespace: infraops-namespace
spec:
  selector:
    app: infraops-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
