apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraops-app
  namespace: infraops-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraops-app
  template:
    metadata:
      labels:
        app: infraops-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest  # Changed to postgres image for better tooling
          command:
            - sh
            - -c
            - |
              until pg_isready -h infraops-postgres.infraops-namespace -p 5432 -U admin; do
                echo "Waiting for postgres to be ready..."
                sleep 2
              done
      containers:
        - name: infraops-app
          image: codex254/infraops:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://infraops-postgres.infraops-namespace:5432/infraops  # Updated port
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin