apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraops-postgres
  namespace: infraops-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraops-postgres
  template:
    metadata:
      labels:
        app: infraops-postgres
    spec:
      containers:
        - name: infraops-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432  # Changed to default PostgreSQL port
          env:
            - name: POSTGRES_DB
              value: infraops
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-p", "5432"]  # Updated port
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc